// ============================================================
// Forecast domain types. Quantities are calculated by deterministic,
// provenance-aware application logic — never generated by an LLM.
// ============================================================

import type { CrowdLevel, SellerFood, SellingItem, SellingPlan } from './database';

export type WeatherCondition = 'rain' | 'clear' | 'hot' | 'other';
export type DataAvailability = 'available' | 'unavailable';
export type ConfidenceLevel = 'Low' | 'Medium' | 'High';
export type ForecastSourceType = 'public_benchmark' | 'personalized' | 'insufficient_evidence';
export type BenchmarkQuantityBasis = 'per_session' | 'per_bazaar_period_revenue_equivalent' | 'not_convertible';

export interface WeatherForecast {
  availability: DataAvailability;
  condition: WeatherCondition | null;
  summary: string;
  source: string | null;
  temperature_c: number | null;
  precipitation_probability: number | null;
  precipitation_mm: number | null;
  weather_code: number | null;
  period_start: string | null;
  period_end: string | null;
}

export interface HistoricalWeatherContext {
  availability: DataAvailability;
  summary: string;
  source: string | null;
  source_url: string | null;
  reference_date: string | null;
  temperature_c: number | null;
  precipitation_mm: number | null;
  weather_code: number | null;
}

export interface CalendarContext {
  availability: DataAvailability;
  is_public_holiday: boolean | null;
  holiday_name: string | null;
  summary: string;
  source: string | null;
  source_url: string | null;
}

export interface TransitContext {
  availability: DataAvailability;
  summary: string;
  station_name: string | null;
  trips: number | null;
  source: string | null;
  source_url: string | null;
}

export interface NearbyEvent {
  name: string;
  distance_km: number | null;
  starts_at: string | null;
  source: string;
  source_url: string | null;
}

export interface PriceInsight {
  availability: 'available' | 'unavailable';
  summary: string;
  source_name: string | null;
  reference_url: string | null;
  item_name: string | null;
  unit: string | null;
  recent_price: number | null;
  price_date: string | null;
  sample_size: number | null;
}

export interface HistoricalSession {
  selling_plan_id: string;
  food_id: string;
  selling_date: string;
  location_name: string | null;
  prepared_quantity: number;
  leftover_quantity: number;
  estimated_sold_quantity: number;
  unit: string;
  crowd_level: CrowdLevel;
}

export interface ForecastPlanContext {
  plan: SellingPlan;
  item: SellingItem;
  food: SellerFood;
  seller_state: string | null;
  seller_city: string | null;
  historical_sessions: HistoricalSession[];
}

export interface DataSourceProvenance {
  source_id: string;
  name: string;
  publisher: string;
  source_url: string;
  license: string | null;
  coverage_start: string | null;
  coverage_end: string | null;
  retrieved_at: string | null;
  what_it_measures: string;
  data_role: 'benchmark' | 'contextual_feature' | 'price_reference';
}

export interface PublicBenchmarkEvidence {
  availability: DataAvailability;
  quantity_basis: BenchmarkQuantityBasis;
  estimate_quantity: number | null;
  estimated_min: number | null;
  estimated_max: number | null;
  sample_size: number;
  population_variance: number | null;
  selected_scope: string | null;
  sales_value_per_stall: number | null;
  persons_engaged_per_stall: number | null;
  serving_price: number | null;
  price_basis: 'seller_declared_menu_price' | 'official_bazaar_item_price' | null;
  methodology: string;
  limitation: string;
  sources: DataSourceProvenance[];
}

export type ForecastSignalKind =
  | 'public_benchmark'
  | 'personal_history'
  | 'weather_context'
  | 'historical_weather_context'
  | 'nearby_event_context'
  | 'holiday_context'
  | 'transit_context';

export interface ForecastSignal {
  kind: ForecastSignalKind;
  label: string;
  availability: DataAvailability;
  role: 'baseline' | 'personal_calibration' | 'context_only';
  detail: string;
}

export interface ForecastConfidence {
  level: ConfidenceLevel;
  score: number;
  comparable_records: number;
  unavailable_context_signals: number;
  detail: string;
}

export interface ForecastResult {
  is_estimate_available: boolean;
  source_type: ForecastSourceType;
  evidence_level: 'benchmark_approximation' | 'personal_observations' | 'insufficient_evidence';
  unit: string;
  baseline_quantity: number | null;
  estimated_min: number | null;
  estimated_max: number | null;
  recommended_quantity: number | null;
  total_adjustment: 0;
  comparable_strategy: string;
  comparable_records: number;
  confidence: ForecastConfidence;
  signals: ForecastSignal[];
  explanation_facts: string[];
  low_data_message: string | null;
  public_benchmark: PublicBenchmarkEvidence;
  weather: WeatherForecast;
  historical_weather: HistoricalWeatherContext;
  calendar_context: CalendarContext;
  transit_context: TransitContext;
  events: NearbyEvent[];
  events_availability: DataAvailability;
  price_insight: PriceInsight;
  model_name: string;
  model_version: string;
  methodology: string;
}
